FILETYPE_ICONS = \
"""filetype-aac
filetype-ai
filetype-bmp
filetype-cs
filetype-css
filetype-csv
filetype-doc
filetype-docx
filetype-exe
filetype-gif
filetype-heic
filetype-html
filetype-java
filetype-jpg
filetype-js
filetype-json
filetype-jsx
filetype-key
filetype-m4p
filetype-md
filetype-mdx
filetype-mov
filetype-mp3
filetype-mp4
filetype-otf
filetype-pdf
filetype-php
filetype-png
filetype-ppt
filetype-pptx
filetype-psd
filetype-py
filetype-raw
filetype-rb
filetype-sass
filetype-scss
filetype-sh
filetype-sql
filetype-svg
filetype-tiff
filetype-tsx
filetype-ttf
filetype-txt
filetype-wav
filetype-woff
filetype-xls
filetype-xlsx
filetype-xml
filetype-yml"""

FILETYPE_EXTENSIONS = [x.split('-')[1] for x in FILETYPE_ICONS.split('\n')]
