# Generated by Django 3.2.14 on 2022-08-16 04:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('markhub', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='privatepublish',
            options={'get_latest_by': 'published', 'ordering': ['user', 'repo', 'branch', 'path'], 'permissions': (('private_repos', 'Work with private repositories'),), 'verbose_name': 'Published file', 'verbose_name_plural': 'Published files'},
        ),
        migrations.AddField(
            model_name='privatepublish',
            name='branch',
            field=models.TextField(default='master', max_length=255, verbose_name='Branch name'),
        ),
        migrations.AlterField(
            model_name='privatepublish',
            name='content',
            field=models.TextField(blank=True, null=True, verbose_name='Markdown content'),
        ),
        migrations.AlterUniqueTogether(
            name='privatepublish',
            unique_together={('user', 'repo', 'branch', 'path')},
        ),
        migrations.AlterIndexTogether(
            name='privatepublish',
            index_together={('user', 'repo', 'branch', 'path')},
        ),
    ]
