# Generated by Django 3.2.14 on 2022-11-23 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('markhub', '0002_auto_20220816_0715'),
    ]

    operations = [
        migrations.AddField(
            model_name='privatepublish',
            name='toc',
            field=models.TextField(blank=True, null=True, verbose_name='Markdown content TOC'),
        ),
    ]
